### ISSUE TITLE
CentOS 7.4: `Exception: 'utf8' codec can't decode byte 0xd0 in position 0: invalid continuation byte`

### ISSUE THREAD

**Issue by e40** [briandorey/tp-link-LB130-Smart-Wi-Fi-Bulb#2]
Running a trimmed down version of `demo.py` after setting `__udp_ip` in `tplight.py` and doing

        light = LB130("192.168.0.211")

in my test script, I get:

    @box[git:master]$ ./test.py 
    Traceback (most recent call last):
      File "./test.py", line 24, in <module>
	main()
      File "./test.py", line 16, in main
	light = LB130("192.168.0.211")
      File "/me/layer/src/import/tp-link-LB130-Smart-Wi-Fi-Bulb/tplight.py", line 78, in __init__
	raise Exception(exception)

    @box[git:master]$ 

Any ideas how to make this problem go away?  Here's the entire `test.py`:

    #!/usr/bin/env python
    # -*- coding: utf-8 -*-
    '''
    Demo for the TP-Link A19-LB130 RBGW WiFi bulb
    '''

    import time
    from tplight import LB130

    def main():
	'''
	Main program function
	'''

	# create an instance of the light with its IP address
	light = LB130("192.168.0.211")

	# fetch the details for the light
	print("Device ID: " + light.device_id)
	print("Alias: " + light.alias)
	print("Wattage: " + str(light.wattage))

    if __name__ == "__main__":
	main()

**Comment by briandorey** [comment]
I have uploaded an update to https://github.com/briandorey/tp-link-LB130-Smart-Wi-Fi-Bulb/blob/master/tplight.py to resolve this issue when running on Python 2

**Comment by e40** [comment]
Thanks!  Still having issues with my LB130(US) with firmware 1.7.1.  I'll submit a pull request, though, as the fix was easier for me to figure out.
